"""Blind OpenAI-compatible provider presets for the generic harness framework."""

from __future__ import annotations

from app.harness.models import (
    HarnessCapabilityProfile,
    HarnessProviderProfile,
    HarnessRequestMapping,
    HarnessStreamMapping,
    HarnessTemplate,
)


def _preset(
    *,
    provider_id: str,
    label: str,
    description: str,
    endpoint_base_url: str,
    path: str = "/chat/completions",
    path_join_policy: str = "append",
    auth_scheme: str = "bearer",
    auth_header: str = "Authorization",
    model: str,
    model_slug_policy: str = "verbatim",
    model_prefix: str = "",
    streaming: bool = True,
    tool_calling: bool = True,
    vision: bool = False,
    responses: bool = False,
    embeddings: bool = False,
    headers: dict[str, str] | None = None,
    unsupported_features: list[str] | None = None,
) -> HarnessTemplate:
    template_id = f"openai_provider_{provider_id}"
    return HarnessTemplate(
        id=template_id,
        label=label,
        integration_class="openai_compatible",
        description=description,
        profile_defaults=HarnessProviderProfile(
            provider_key=provider_id,
            label=label,
            integration_class="openai_compatible",
            endpoint_base_url=endpoint_base_url,
            auth_scheme=auth_scheme,  # type: ignore[arg-type]
            auth_header=auth_header,
            template_id=template_id,
            model_slug_policy=model_slug_policy,  # type: ignore[arg-type]
            model_prefix=model_prefix,
            models=[model],
            request_mapping=HarnessRequestMapping(
                path=path,
                path_join_policy=path_join_policy,  # type: ignore[arg-type]
                headers=headers or {},
            ),
            stream_mapping=HarnessStreamMapping(enabled=streaming),
            capabilities=HarnessCapabilityProfile(
                streaming=streaming,
                tool_calling=tool_calling,
                vision=vision,
                responses=responses,
                embeddings=embeddings,
                discovery_support=False,
                model_source="manual",
                unsupported_features=list(unsupported_features or []),
            ),
        ),
    )


OPENAI_PROVIDER_PRESET_TEMPLATES: dict[str, HarnessTemplate] = {
    "azure_openai": _preset(
        provider_id="azure_openai",
        label="Azure OpenAI / Foundry",
        description="Azure OpenAI-compatible endpoint with explicit `api-key` header semantics.",
        endpoint_base_url="https://YOUR_RESOURCE_NAME.openai.azure.com/openai/v1",
        auth_scheme="api_key_header",
        auth_header="api-key",
        model="gpt-4.1-mini",
        responses=True,
        vision=True,
        embeddings=True,
    ),
    "gemini_openai": _preset(
        provider_id="gemini_openai",
        label="Google Gemini OpenAI-compatible",
        description="Gemini OpenAI-compatible endpoint under the Google Generative Language API.",
        endpoint_base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        model="gemini-2.5-flash",
        responses=False,
        vision=True,
        embeddings=True,
        unsupported_features=["files"],
    ),
    "google_vertex_ai": _preset(
        provider_id="google_vertex_ai",
        label="Google Vertex AI OpenAI-compatible",
        description="Vertex AI OpenAI-compatible endpoint with OAuth bearer auth and project/location-scoped base URL.",
        endpoint_base_url="https://LOCATION-aiplatform.googleapis.com/v1/projects/PROJECT_ID/locations/LOCATION/endpoints/openapi",
        model="google/gemini-2.5-pro",
        vision=True,
        unsupported_features=["files"],
    ),
    "groq": _preset(
        provider_id="groq",
        label="Groq",
        description="Groq OpenAI-compatible endpoint with `/openai/v1` root and fast SSE streaming.",
        endpoint_base_url="https://api.groq.com/openai/v1",
        path_join_policy="dedupe_openai_v1",
        model="llama-3.3-70b-versatile",
        responses=True,
        unsupported_features=["files parity is partial"],
    ),
    "deepseek": _preset(
        provider_id="deepseek",
        label="DeepSeek",
        description="DeepSeek OpenAI-compatible chat endpoint.",
        endpoint_base_url="https://api.deepseek.com/v1",
        model="deepseek-chat",
    ),
    "mistral": _preset(
        provider_id="mistral",
        label="Mistral AI",
        description="Mistral OpenAI-compatible chat path for the generic harness.",
        endpoint_base_url="https://api.mistral.ai/v1",
        model="mistral-small-latest",
        unsupported_features=["native Mistral API features outside chat parity"],
    ),
    "minimax": _preset(
        provider_id="minimax",
        label="MiniMax",
        description="MiniMax text chatcompletion_v2 endpoint on the official bearer-auth API surface.",
        endpoint_base_url="https://api.minimaxi.com/v1",
        path="/text/chatcompletion_v2",
        model="MiniMax-M2.7",
        streaming=False,
        tool_calling=False,
        responses=False,
        embeddings=False,
        unsupported_features=[
            "streaming parity not wired in the generic preset",
            "tool-calling parity not documented on the shipped chatcompletion_v2 bridge",
        ],
    ),
    "together": _preset(
        provider_id="together",
        label="Together AI",
        description="Together AI OpenAI-compatible chat endpoint.",
        endpoint_base_url="https://api.together.xyz/v1",
        model="meta-llama/Llama-3.3-70B-Instruct-Turbo",
    ),
    "fireworks": _preset(
        provider_id="fireworks",
        label="Fireworks AI",
        description="Fireworks OpenAI-compatible inference path rooted below `/inference/v1`.",
        endpoint_base_url="https://api.fireworks.ai/inference/v1",
        model="accounts/fireworks/models/llama-v3p1-8b-instruct",
    ),
    "cerebras": _preset(
        provider_id="cerebras",
        label="Cerebras",
        description="Cerebras OpenAI-compatible inference API.",
        endpoint_base_url="https://api.cerebras.ai/v1",
        model="llama3.1-8b",
    ),
    "openrouter": _preset(
        provider_id="openrouter",
        label="OpenRouter",
        description="OpenRouter aggregator preset with vendor/model slug defaults and recommended metadata headers.",
        endpoint_base_url="https://openrouter.ai/api/v1",
        model="gpt-4o-mini",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="openai",
        responses=False,
        embeddings=False,
        headers={"HTTP-Referer": "https://forgeframe.local", "X-OpenRouter-Title": "ForgeFrame"},
        unsupported_features=["responses parity varies by upstream model"],
    ),
    "vercel_ai_gateway": _preset(
        provider_id="vercel_ai_gateway",
        label="Vercel AI Gateway",
        description="Vercel AI Gateway preset with vendor/model slug defaults for routed providers.",
        endpoint_base_url="https://ai-gateway.vercel.sh/v1",
        model="gpt-4o-mini",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="openai",
        unsupported_features=["responses parity varies by upstream model"],
    ),
    "nous": _preset(
        provider_id="nous",
        label="Nous Portal",
        description="Nous Portal aggregator preset with vendor/model slug inference for multi-vendor routed models.",
        endpoint_base_url="https://inference-api.nousresearch.com/v1",
        model="gpt-5.4",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="openai",
        unsupported_features=["live account/runtime evidence still depends on Nous OAuth or agent-key proof"],
    ),
    "kilocode": _preset(
        provider_id="kilocode",
        label="KiloCode",
        description="KiloCode gateway preset with vendor/model slug defaults.",
        endpoint_base_url="https://api.kilo.ai/api/gateway",
        path="/chat/completions",
        model="gpt-4o-mini",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="openai",
        unsupported_features=["responses parity not documented"],
    ),
    "huggingface": _preset(
        provider_id="huggingface",
        label="Hugging Face Router",
        description="Hugging Face Router preset for OpenAI-compatible routed chat.",
        endpoint_base_url="https://router.huggingface.co/v1",
        model="meta-llama/Llama-3.3-70B-Instruct",
        embeddings=False,
    ),
    "nvidia_nim": _preset(
        provider_id="nvidia_nim",
        label="NVIDIA NIM",
        description="NVIDIA NIM preset using the OpenAI-compatible hosted inference endpoint.",
        endpoint_base_url="https://integrate.api.nvidia.com/v1",
        model="meta/llama-3.1-8b-instruct",
    ),
    "arcee": _preset(
        provider_id="arcee",
        label="Arcee AI",
        description="Arcee AI OpenAI-compatible preset.",
        endpoint_base_url="https://conductor.arcee.ai/api/v1",
        model="arcee-ai/coder-large",
    ),
    "alibaba_dashscope": _preset(
        provider_id="alibaba_dashscope",
        label="Alibaba DashScope",
        description="DashScope compatible-mode preset below `/compatible-mode/v1`.",
        endpoint_base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        model="qwen-max",
    ),
    "kimi_moonshot": _preset(
        provider_id="kimi_moonshot",
        label="Kimi / Moonshot",
        description="Moonshot OpenAI-compatible endpoint.",
        endpoint_base_url="https://api.moonshot.ai/v1",
        model="moonshot-v1-8k",
    ),
    "perplexity": _preset(
        provider_id="perplexity",
        label="Perplexity Sonar",
        description="Perplexity chat-completions preset for Sonar-style responses.",
        endpoint_base_url="https://api.perplexity.ai",
        path="/chat/completions",
        model="sonar-pro",
        unsupported_features=["responses parity not documented"],
    ),
    "ollama_cloud": _preset(
        provider_id="ollama_cloud",
        label="Ollama Cloud",
        description="Ollama Cloud remote OpenAI-compatible endpoint.",
        endpoint_base_url="https://ollama.com/v1",
        model="llama3.2",
        responses=True,
        embeddings=True,
    ),
    "localai": _preset(
        provider_id="localai",
        label="LocalAI",
        description="LocalAI local OpenAI-compatible runtime.",
        endpoint_base_url="http://127.0.0.1:8080/v1",
        auth_scheme="none",
        model="local-model",
        responses=False,
        embeddings=True,
    ),
    "llama_cpp": _preset(
        provider_id="llama_cpp",
        label="llama.cpp server",
        description="llama.cpp server preset with OpenAI-compatible endpoints.",
        endpoint_base_url="http://127.0.0.1:8080/v1",
        auth_scheme="none",
        model="llama.cpp",
        responses=True,
        embeddings=True,
    ),
    "llama_cpp_python": _preset(
        provider_id="llama_cpp_python",
        label="llama-cpp-python server",
        description="llama-cpp-python OpenAI-compatible server preset.",
        endpoint_base_url="http://127.0.0.1:8000/v1",
        auth_scheme="none",
        model="llama-cpp-python",
    ),
    "vllm": _preset(
        provider_id="vllm",
        label="vLLM",
        description="vLLM OpenAI-compatible server preset.",
        endpoint_base_url="http://127.0.0.1:8000/v1",
        auth_scheme="none",
        model="meta-llama/Llama-3.1-8B-Instruct",
        embeddings=True,
    ),
    "xai": _preset(
        provider_id="xai",
        label="xAI",
        description="xAI OpenAI-compatible endpoint.",
        endpoint_base_url="https://api.x.ai/v1",
        model="grok-3-mini",
    ),
    "zai": _preset(
        provider_id="zai",
        label="Z.AI / GLM",
        description="Z.AI OpenAI-compatible endpoint.",
        endpoint_base_url="https://api.z.ai/v1",
        model="glm-4.5",
    ),
    "xiaomi_mimo": _preset(
        provider_id="xiaomi_mimo",
        label="Xiaomi MiMo",
        description="Xiaomi MiMo OpenAI-compatible endpoint.",
        endpoint_base_url="https://api.mimo.xiaomi.com/v1",
        model="mimo-chat",
    ),
    "opencode_zen": _preset(
        provider_id="opencode_zen",
        label="OpenCode Zen",
        description="OpenCode Zen gateway preset on the OpenAI-like `/chat/completions` surface.",
        endpoint_base_url="https://opencode.ai/zen/v1",
        model="gpt-4o-mini",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="openai",
        unsupported_features=["special native OpenCode behavior outside the OpenAI-like path is not wired in this preset"],
    ),
    "opencode_go": _preset(
        provider_id="opencode_go",
        label="OpenCode Go",
        description="OpenCode Go mixed gateway preset on the OpenAI-like `/chat/completions` surface.",
        endpoint_base_url="https://opencode.ai/zen/go/v1",
        model="glm-4.5",
        model_slug_policy="infer_vendor_if_missing",
        model_prefix="z-ai",
        unsupported_features=["mixed `/messages` branch is not wired; this preset only targets the OpenAI-like path"],
    ),
}
