/**
 * Provider domain API surface extracted from admin API.
 *
 * Note: `SecretStorageControl` is intentionally omitted from this barrel
 * to avoid name collision with the security barrel. Import it from
 * `domain/security` instead.
 */
export {
  activateHarnessProfile,
  activateProvider,
  createProvider,
  deactivateHarnessProfile,
  deactivateProvider,
  deleteHarnessProfile,
  dryRunHarness,
  fetchClientDrilldown,
  fetchCompatibilityMatrix,
  fetchHarnessExport,
  fetchHarnessProfiles,
  fetchHarnessRuns,
  fetchHarnessSnapshot,
  fetchHarnessTemplates,
  fetchModelRegister,
  fetchOauthAccountOperations,
  fetchOauthAccountTargets,
  fetchOauthOnboarding,
  fetchProductAxisTargets,
  fetchProviderControlPlane,
  fetchProviderDrilldown,
  fetchProviderTargets,
  importHarnessConfig,
  patchHealthConfig,
  previewHarness,
  probeAllOauthAccountProviders,
  probeHarness,
  probeOauthAccountProvider,
  rollbackHarnessProfile,
  runHealthChecks,
  syncOauthAccountBridgeProfiles,
  syncProviders,
  updateProvider,
  updateProviderTarget,
  upsertHarnessProfile,
  verifyHarnessProfile,
  type AdminModelRegisterRecord,
  type AdminModelRegisterResponse,
  type CapabilityEvidenceRecord,
  type CompatibilityMatrixRow,
  type HarnessCapabilityProfile,
  type HarnessErrorMapping,
  type HarnessProfile,
  type HarnessRequestMapping,
  type HarnessResponseMapping,
  type HarnessRun,
  type HarnessStreamMapping,
  type HarnessTemplate,
  type HarnessVerificationResult,
  type HealthConfig,
  type ManagedModel,
  type OauthOnboardingTarget,
  type OauthTargetStatus,
  type OpenAICompatibilityCorpusClass,
  type OpenAICompatibilitySignoffResponse,
  type OpenAICompatibilitySignoffRow,
  type OpenAICompatibilityStatus,
  type OpenAICompatibilitySummary,
  type ProductAxisTarget,
  type ProviderCatalogEntry,
  type ProviderCatalogEvidenceClass,
  type ProviderCatalogEvidenceRecord,
  type ProviderCatalogEvidenceStatus,
  type ProviderCatalogSignoffRecord,
  type ProviderCatalogSignoffStatus,
  type ProviderCatalogSummary,
  type ProviderCapabilityEvidenceRecord,
  type ProviderClassDescriptor,
  type ProviderClassKey,
  type ProviderControlItem,
  type ProviderControlPlaneResponse,
  type ProviderTargetRecord,
  type ProviderTargetRegisterResponse,
} from "../admin/providers";
