/**
 * Provider domain API surface extracted from admin API.
 */
export {
  createProvider,
  deleteHarnessProfile,
  fetchCompatibilityMatrix,
  fetchHarnessExport,
  fetchHarnessProfiles,
  fetchHarnessRuns,
  fetchHarnessSnapshot,
  fetchModelRegister,
  fetchOauthAccountOperations,
  fetchOauthAccountTargets,
  fetchOauthOnboarding,
  fetchProviderControlPlane,
  fetchProviderDrilldown,
  fetchProviderTargets,
  fetchProductAxisTargets,
  runHealthChecks,
  updateProvider,
  updateProviderTarget,
  type AdminModelRegisterResponse,
  type ManagedModel,
  type ProviderCatalogEntry,
  type ProviderCatalogEvidenceClass,
  type ProviderCatalogEvidenceRecord,
  type ProviderCatalogEvidenceStatus,
  type ProviderCatalogSignoffRecord,
  type ProviderCatalogSignoffStatus,
  type ProviderCatalogSummary,
  type ProviderCapabilityEvidenceRecord,
  type ProviderClassDescriptor,
  type ProviderClassKey,
  type ProviderControlItem,
  type ProviderControlPlaneResponse,
  type ProviderTargetRecord,
  type ProviderTargetRegisterResponse,
} from "../admin/providers";
