/**
 * Security domain API surface extracted from admin API.
 */
export {
  approveElevatedAccessRequest,
  cancelElevatedAccessRequest,
  createAdminUser,
  createBreakGlassRequest,
  createImpersonationRequest,
  deleteAdminUserMembership,
  fetchAdminSessions,
  fetchAdminUserMemberships,
  fetchAdminUsers,
  fetchElevatedAccessRequests,
  fetchProviderSecretPosture,
  fetchSecurityBootstrap,
  issueElevatedAccessRequest,
  recordSecretRotation,
  rejectElevatedAccessRequest,
  revokeAdminSession,
  rotateAdminPassword,
  updateAdminUser,
  upsertAdminUserMembership,
  type AdminPasswordRotationPayload,
  type AdminSecuritySession,
  type AdminInstanceMembership,
  type ElevatedAccessApproverPosture,
  type ElevatedAccessRequest,
  type ElevatedAccessRequestType,
  type HarnessSecretPosture,
  type SecretStorageControl,
  type SecurityBlocker,
  type SecurityBootstrapResponse,
  type SecurityBootstrapStatus,
  type SecurityCredentialPolicy,
  type SecurityRotationEvent,
  type SecuritySecretPosture,
} from "../admin/security";
